server:
  port : 8081

web-client:
  baseUrl: "http://localhost:8080"
  port: 8080

shipment:
  baseUrl: "http://localhost"
  port: 8080

track:
  baseUrl: "http://localhost"
  port: 8080

pricing:
  baseUrl: "http://localhost"
  port: 8080
